INSERT INTO TELEFONOS_PROVEEDOR (ID_PROVEEDOR,TELEFONO)
SELECT PROVEEDOR.ID, TELEFONOS_TEMP.TELEFONO
FROM TELEFONOS_TEMP CROSS JOIN PROVEEDOR 
WHERE TELEFONOS_TEMP.NOMBRE_PROVEEDOR = PROVEEDOR.NOMBRE
GO
DROP TABLE TELEFONOS_TEMP