CREATE TABLE [dbo].[AUTOMOVIL]
(
	[MODELO] VARCHAR(20) NOT NULL, 
    [ANO] NCHAR(4) NOT NULL, 
    CONSTRAINT CH_ANO CHECK (LEN(ANO) = 4),
    [DETALLE] VARCHAR(50) NOT NULL,
    [FABRICANTE] INT NOT NULL, 
    CONSTRAINT FK_AUTO_FABAUTO FOREIGN KEY ([FABRICANTE]) REFERENCES FAB_AUTOS (ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT PK_AUTO PRIMARY KEY (MODELO, ANO)
)
