CREATE TABLE [dbo].[AUTOMOVIL]
(
	[MODELO] VARCHAR(20) NOT NULL, 
    [ANO] NCHAR(4) NOT NULL, 
    [DETALLE] VARCHAR(50) NOT NULL,
    [NOMBRE_FAB] VARCHAR(50) NOT NULL, 
    FOREIGN KEY (NOMBRE_FAB) REFERENCES FAB_AUTOS (NOMBRE),
    PRIMARY KEY (MODELO, ANO)
)
