CREATE TABLE [dbo].[AUTOMOVIL]
(
    [ID] INT NOT NULL IDENTITY, 
	[MODELO] NVARCHAR(20) NOT NULL,
    [ANO] NCHAR(4) NOT NULL, 
    CONSTRAINT CH1_ANO CHECK (LEN(ANO) = 4),
    CONSTRAINT CH2_ANO CHECK (ANO NOT LIKE '%[^0-9]%'),
    [DETALLE] NVARCHAR(50) NOT NULL,
    [ID_FABRICANTE] INT NOT NULL, 
    CONSTRAINT FK_AUTO_FABAUTO FOREIGN KEY ([ID_FABRICANTE]) REFERENCES FAB_AUTOS (ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT PK_AUTO PRIMARY KEY (ID),
    CONSTRAINT AK_AUTO UNIQUE (MODELO, ANO)
)
