CREATE TABLE [dbo].[CLIENTE]
(
    [CEDULA] NCHAR(10) NOT NULL,
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [ESTADO] VARCHAR(10) NOT NULL, 
    CHECK ([ESTADO] IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO')), 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    PRIMARY KEY CLUSTERED ([CEDULA] ASC)
)
