CREATE TABLE [dbo].[CLIENTE_PERSONA]
(
    [CEDULA] NCHAR(9) NOT NULL,
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [ESTADO] NCHAR(1) NOT NULL, 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    PRIMARY KEY CLUSTERED ([CEDULA] ASC)
)
