CREATE TABLE [dbo].[CLIENTE] (
    [CEDULA] NCHAR(10) NOT NULL,
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [ESTADO] NCHAR(1) NOT NULL, 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    PRIMARY KEY CLUSTERED ([CEDULA] ASC)
);
