CREATE TABLE [dbo].[CORRESPONDENCIA]
(
	[ID_PARTE] INT NOT NULL, 
    [ID_AUTOMOVIL] INT NOT NULL
	CONSTRAINT FK_CORR_PARTE FOREIGN KEY (ID_PARTE) REFERENCES PARTE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK_CORR_AUTO FOREIGN KEY ([ID_AUTOMOVIL]) REFERENCES AUTOMOVIL (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT PK_CORR PRIMARY KEY (ID_PARTE, ID_AUTOMOVIL)
)
