CREATE TABLE [dbo].[DETALLE]
(
    [ID_ORDEN] INT NOT NULL,
    [ID] INT NOT NULL,
    [PRECIO] DECIMAL(18, 2) NOT NULL, 
    [CANTIDAD] INT NOT NULL, 
    [ID_PARTE] INT NOT NULL, 
    [NOMBRE_PROVEEDOR] VARCHAR(50) NOT NULL, 
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN (ID),
    FOREIGN KEY (ID_PARTE) REFERENCES PARTE (ID),
    FOREIGN KEY (NOMBRE_PROVEEDOR) REFERENCES PROVEEDOR(NOMBRE),
    PRIMARY KEY (ID, ID_ORDEN)
)
