CREATE TABLE ORDEN
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [MONTO_BASE] DECIMAL(18, 2) NOT NULL DEFAULT 0, 
    CHECK ([MONTO_BASE] >= 0),
    [MONTO_FINAL] DECIMAL(18, 2) NOT NULL DEFAULT 0, 
    CHECK ([MONTO_FINAL] >= 0),
    [FECHA] DATE NOT NULL DEFAULT GETDATE(), 
    [CEDULA_PERSONA] NCHAR(9) NULL,
    [CEDULA_ORGANIZACION] NCHAR(10) NULL, 
    FOREIGN KEY ([CEDULA_PERSONA]) REFERENCES PERSONA (CEDULA),
    FOREIGN KEY ([CEDULA_ORGANIZACION]) REFERENCES ORGANIZACION (CEDULA),
    CHECK (([CEDULA_PERSONA] IS NULL OR [CEDULA_ORGANIZACION] IS NULL) AND NOT ([CEDULA_PERSONA] IS NULL AND [CEDULA_ORGANIZACION] IS NULL))
)
