CREATE TABLE [dbo].[ORGANIZACION]
(
    [CEDULA_JUR] NCHAR(10) NOT NULL,
    CONSTRAINT CH_CEDJ CHECK (LEN([CEDULA_JUR]) = 10),
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    [NOMBRE_CONTACTO] VARCHAR(50) NOT NULL,
    [CARGO_CONTACTO] VARCHAR(50) NOT NULL,
    [ID_CLIENTE] INT NOT NULL, 
    CONSTRAINT FK_ORG_CL FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT PK_ORG PRIMARY KEY CLUSTERED ([CEDULA_JUR] ASC)
)
