CREATE TABLE [dbo].[ORGANIZACION]
(
    [CEDULA] NCHAR(10) NOT NULL,
    CHECK (LEN(CEDULA) = 10),
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [ESTADO] VARCHAR(10) NOT NULL, 
    CHECK ([ESTADO] IN ('ACTIVO', 'INACTIVO', 'SUSPENDIDO')), 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    [NOMBRE_CONTACTO] VARCHAR(50) NOT NULL,
    [CARGO_CONTACTO] VARCHAR(50) NOT NULL,
    PRIMARY KEY CLUSTERED ([CEDULA] ASC)
)
