CREATE TABLE [dbo].[PARTE]
(
	[ID] INT NOT NULL IDENTITY, 
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [ID_FABRICANTE] INT NOT NULL,
    [ID_MARCA] INT NOT NULL,
    [ID_AUTO] INT NOT NULL, 
    CONSTRAINT FK_PARTE_FABPARTE FOREIGN KEY ([ID_FABRICANTE]) REFERENCES FAB_PARTES (ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_PARTE_MARCA FOREIGN KEY ([ID_MARCA]) REFERENCES MARCA (ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK_PARTE_AUTO FOREIGN KEY (ID_AUTO) REFERENCES AUTOMOVIL (ID)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT PK_PARTE PRIMARY KEY (ID)
)
