CREATE TABLE [dbo].[PERSONA]
(
    [CEDULA] NCHAR(9) NOT NULL,
    CONSTRAINT CH_CED CHECK (LEN(CEDULA) = 9),
    [NOMBRE] VARCHAR(50) NOT NULL, 
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
    [ID_CLIENTE] INT NOT NULL, 
    CONSTRAINT FK_PER_CL FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT PK_PER PRIMARY KEY CLUSTERED ([CEDULA] ASC)
)
