CREATE TABLE [dbo].[PERSONA]
(
    [CEDULA] NCHAR(9) NOT NULL,
    CONSTRAINT CH1_CED CHECK (LEN(CEDULA) = 9),
    CONSTRAINT CH2_CED CHECK (CEDULA NOT LIKE '%[^0-9]%'),
    [NOMBRE] NVARCHAR(50) NOT NULL, 
    [DIRECCION] NVARCHAR(50) NOT NULL, 
    [CIUDAD] NVARCHAR(20) NOT NULL, 
    [ID_CLIENTE] INT NOT NULL, 
    CONSTRAINT FK_PER_CL FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT PK_PER PRIMARY KEY CLUSTERED ([CEDULA] ASC)
)
