CREATE TABLE [dbo].[PROVEEDOR]
(
	[ID] INT NOT NULL IDENTITY, 
	[NOMBRE] NVARCHAR(50) NOT NULL, 
    [NOMBRE_CONTACTO] NVARCHAR(50) NOT NULL,
    [DIRECCION] NVARCHAR(50) NOT NULL, 
    [CIUDAD] NVARCHAR(20) NOT NULL,
    CONSTRAINT AK_PROV UNIQUE (NOMBRE),
    CONSTRAINT PK_PROV PRIMARY KEY (ID)
)
