CREATE TABLE [dbo].[PROVEEDOR]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
	[NOMBRE] VARCHAR(50) NOT NULL UNIQUE, 
    [NOMBRE_CONTACTO] VARCHAR(50) NOT NULL,
    [DIRECCION] VARCHAR(50) NOT NULL, 
    [CIUDAD] VARCHAR(50) NOT NULL, 
)
