CREATE TABLE [dbo].[PROVISION]
(
	[ID_PARTE] INT NOT NULL, 
    [NOMBRE_PROVEEDOR] VARCHAR(50) NOT NULL,
	[PRECIO_COMPRA] DECIMAL(18, 2) NOT NULL DEFAULT 0,
    CHECK ([PRECIO_COMPRA] >= 0),
    [POR_GANANCIA] DECIMAL(18, 2) NOT NULL DEFAULT 0,
    CHECK ([POR_GANANCIA] >= 0 AND [POR_GANANCIA] <= 100),
    FOREIGN KEY (ID_PARTE) REFERENCES PARTE (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (NOMBRE_PROVEEDOR) REFERENCES PROVEEDOR (NOMBRE)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    PRIMARY KEY (ID_PARTE, NOMBRE_PROVEEDOR)
)
