INSERT INTO ESTADO(TIPO) VALUES('ACTIVO')
INSERT INTO ESTADO(TIPO) VALUES('INACTIVO')

INSERT INTO FAB_AUTOS(NOMBRE) VALUES('Toyota')

INSERT INTO AUTOMOVIL(ID_FABRICANTE, MODELO, ANO, DETALLE) VALUES(1, 'Yaris', 2008, 'Subcompact')

INSERT INTO PROVEEDOR(NOMBRE, DIRECCION, CIUDAD, NOMBRE_CONTACTO) VALUES('Super Repuestos', '150 E Plaza Santa Rosa', 'Liberia', 'Irene Carranza Pellicer')

INSERT INTO FAB_PARTES(NOMBRE) VALUES('Auto Spare Parts')

INSERT INTO MARCA(NOMBRE) VALUES('Walker')