CREATE TABLE TELEFONOS_CLIENTE
(
	[CEDULA_CLIENTE] NCHAR(10) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	PRIMARY KEY (CEDULA_CLIENTE, TELEFONO),
    FOREIGN KEY ([CEDULA_CLIENTE]) REFERENCES CLIENTE (CEDULA)
)
