CREATE TABLE [dbo].[TELEFONOS_ORGANIZACION]
(
	[CEDULA_ORGANIZACION] NCHAR(10) NOT NULL, 
    [TELEFONO] NCHAR(8) NOT NULL, 
	CHECK (LEN(TELEFONO) = 8),
	FOREIGN KEY ([CEDULA_ORGANIZACION]) REFERENCES ORGANIZACION ([CEDULA_JUR])
	    ON DELETE CASCADE 
        ON UPDATE CASCADE,
	PRIMARY KEY ([CEDULA_ORGANIZACION], TELEFONO)
)
