CREATE TABLE [dbo].[TELEFONOS_CL_ORGANIZACION]
(
	[CEDULA_CL_ORGANIZACION] NCHAR(10) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	FOREIGN KEY ([CEDULA_CL_ORGANIZACION]) REFERENCES CLIENTE_ORGANIZACION (CEDULA),
	PRIMARY KEY (CEDULA_CL_ORGANIZACION, TELEFONO)
)
