CREATE TABLE [dbo].[TELEFONOS_CLIENTE]
(
	[CEDULA_CLIENTE] NCHAR(10) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	FOREIGN KEY ([CEDULA_CLIENTE]) REFERENCES CLIENTE (CEDULA),
	PRIMARY KEY ([CEDULA_CLIENTE], TELEFONO)
)
