CREATE TABLE [dbo].[TELEFONOS_PROVEEDOR]
(
	[NOMBRE_PROVEEDOR] VARCHAR(50) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	CONSTRAINT CH_TELPROV CHECK (LEN(TELEFONO) = 8),
	CONSTRAINT FK_TELPROV_PROV FOREIGN KEY ([NOMBRE_PROVEEDOR]) REFERENCES PROVEEDOR (NOMBRE)
	    ON DELETE NO ACTION
        ON UPDATE CASCADE,
	CONSTRAINT PK_TELPROV PRIMARY KEY ([NOMBRE_PROVEEDOR], TELEFONO)
)
