CREATE TABLE [dbo].[TELEFONOS_PROVEEDOR]
(
	[NOMBRE_PROVEEDOR] VARCHAR(50) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	CHECK (LEN(TELEFONO) = 8),
	FOREIGN KEY ([NOMBRE_PROVEEDOR]) REFERENCES PROVEEDOR (NOMBRE)
	    ON DELETE NO ACTION
        ON UPDATE CASCADE,
	PRIMARY KEY ([NOMBRE_PROVEEDOR], TELEFONO)
)
