CREATE TABLE [dbo].[TELEFONOS_CL_PERSONA]
(
	[CEDULA_CL_PERSONA] NCHAR(9) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	FOREIGN KEY ([CEDULA_CL_PERSONA]) REFERENCES CLIENTE_PERSONA (CEDULA),
	PRIMARY KEY ([CEDULA_CL_PERSONA], TELEFONO)
)
