CREATE TABLE [dbo].[TELEFONOS_PROVEEDOR]
(
	[NOMBRE_PROVEEDOR] VARCHAR(50) NOT NULL , 
    [TELEFONO] NCHAR(8) NOT NULL, 
	FOREIGN KEY ([NOMBRE_PROVEEDOR]) REFERENCES PROVEEDOR (NOMBRE),
	PRIMARY KEY ([NOMBRE_PROVEEDOR], TELEFONO)
)
